import os

BOT_TOKEN = os.environ["BOT_TOKEN"]
OPENROUTER_API_KEY = os.environ("OPENROUTER_API_KEY")

UPDATE_POSTED_CLUSTERS = False
RELATED_CLUSTERS_ENABLED = False
SEND_DISCUSSION_MESSAGES = False
FILTER_TITILE_RU_ONLY = False
FILTER_TITILE_OBSCENE = False
